### ISSUE TITLE
How to deal with "401 JWT expired"

### ISSUE THREAD

**Issue by DangerLifter** [ho-nl/BolCom_RetailerApi#30]
How to properly deal with "401 JWT expired" in long script?
Injection RefreshToken GrantType in constructor of BolCom\RetailerApi\Client\Oauth2Middleware did not help.

`Exception: Client error: `GET https://api.bol.com/retailer/shipments?page=1&order-id=2547266220` resulted in a `401 JWT expired at 2020-03-24T10:32:19Z. Current time: 2020-03-24T10:33:00Z, a difference of 40501 milliseconds.  Allowed clock skew: 1000 milliseconds.: ` response:
 (truncated...)

#0 /var/www/html/bolcom_app_nonarbitrage/vendor/bol-com/retailer-api/src/Client/RequestException.php(47): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/html/bolcom_app_nonarbitrage/vendor/bol-com/retailer-api/src/Client/RequestExceptionMiddleware.php(25): BolCom\RetailerApi\Client\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#2 /var/www/html/bolcom_app_nonarbitrage/vendor/guzzlehttp/promises/src/Promise.php(203): BolCom\RetailerApi\Client\RequestExceptionMiddleware->BolCom\RetailerApi\Client\{closure}(Object(GuzzleHttp\Psr7\Response))
#3 /var/www/html/bolcom_app_nonarbitrage/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#4 /var/www/html/bolcom_app_nonarbitrage/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#5 /var/www/html/bolcom_app_nonarbitrage/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#6 /var/www/html/bolcom_app_nonarbitrage/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#7 /var/www/html/bolcom_app_nonarbitrage/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#8 /var/www/html/bolcom_app_nonarbitrage/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#9 /var/www/html/bolcom_app_nonarbitrage/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /var/www/html/bolcom_app_nonarbitrage/vendor/guzzlehttp/guzzle/src/Client.php(183): GuzzleHttp\Promise\Promise->wait()
#11 /var/www/html/bolcom_app_nonarbitrage/vendor/guzzlehttp/guzzle/src/Client.php(96): GuzzleHttp\Client->request('get', 'shipments', Array)
#12 /var/www/html/bolcom_app_nonarbitrage/vendor/bol-com/retailer-api/src/Handler/Shipment/GetShipmentListHandler.php(40): GuzzleHttp\Client->__call('get', Array)
`

**Comment by nocturnalfrog** [comment]
Is there a solution for this issue yet? 
We also run into this problem.

**Comment by nocturnalfrog** [comment]
@JeroenVanLeusden,
Any chance you could have a look at this?

**Comment by JeroenVanLeusden** [comment]
Not any time soon, sorry. Will investigate when I've got some time but cannot tell you when exactly. A RefreshToken might work or a retry mechanism has to be implemented I guess.
